
/* Drop Tables */

DROP TABLE JSP.BBS CASCADE CONSTRAINTS;
DROP TABLE JSP.DATAROOM CASCADE CONSTRAINTS;
DROP TABLE JSP.USERS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE JSP.BBS
(
	ID  NOT NULL,
	USERNAME varchar2(10 char),
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	HITCOUNT  DEFAULT 0,
	POSTDATE date DEFAULT SYSDATE,
	CONSTRAINT SYS_C009757 PRIMARY KEY (ID)
);


CREATE TABLE JSP.DATAROOM
(
	ID  NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	PASSWORD varchar2(10 char) NOT NULL,
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	FILES nvarchar2(200) NOT NULL,
	DOWNCOUNT  DEFAULT 0,
	POSTDATE date DEFAULT sysdate
,
	CONSTRAINT SYS_C0010192 PRIMARY KEY (ID)
);


CREATE TABLE JSP.USERS
(
	USERNAME varchar2(10 char) NOT NULL,
	PASSWORD varchar2(10 char) NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	REGIDATE date DEFAULT SYSDATE
,
	CONSTRAINT SYS_C009754 PRIMARY KEY (USERNAME)
);



/* Create Foreign Keys */

ALTER TABLE JSP.BBS
	ADD CONSTRAINT SYS_C009758 FOREIGN KEY (USERNAME)
	REFERENCES JSP.USERS (USERNAME)
;



